version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage for MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: django-app
    command: ["gunicorn", "--workers=3", "--bind", "0.0.0.0:8000", "django_docker.wsgi:application"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ensures MySQL is ready before starting Django
    env_file:
      - .env

volumes:
  mysql_data:
